# Aula 02 - Python

## Dados numéricos

In [23]:
# Variável inteira - a # é utilizada para fazer comentários sem afetar o código
a = 1 #definindo o valor de a
print('Valor de a = '+str(a)) #print serve para mostrar, entre os ' ' está o que deve mostrar escrito (não comando) e o +str(a) que é para escrever o valor de a
type(a) #serve para escrever o tipo de varável que é "a"

Valor de a = 1


int

In [6]:
# Variável dupla precisão
b = 1.0 #definindo a variável b
print(b) #escrever o valor da variável b
type(b) #serve para escrever o tipo de varável que é "b"

1.0


float

In [7]:
# Converter float para int
c = int(b) #transformar b que era uma variável de dupla precisão em um número inteiro
print(c) #escrever o valor da variável c
type(c) #serve para escrever o tipo de varável que é "c"

1


int

In [9]:
# Delacrando nan
import numpy as np #importando a biblioteca NumPy com o nome np
d = np.nan #definindo a variável d como nan, um valor especial utilizado para representar a falta de um valor numérico
print(d) #escrever a variável d
type(d) #serve para escrever o tipo de varável que é "d"

nan


float

In [10]:
# Operação com NaN
e = d*1 #multiplicando nan com 1
print(e) #escrever a variável e
e = d+1 #somando nan com 1
print(e) #escrever a variável e
e = np.nansum([d,1]) #somando os valores contidos na lista [d, 1], ignorando qualquer valor NaN na operação de soma
print(e) #escrever a variável e

nan
nan
1.0


## Dados numéricos

In [16]:
# Declaração de variável texto
f = 'Fábio' #definindo a variável f como texto (str) com o uso de ''
g = "Gabriel" #definindo a variável g como texto (str) com o uso de "", mostrando que funciona das duas formas de aspas
print(f) #escrever a variável f
print(type(f)) #serve para escrever o tipo de varável que é "f" (conferindo se foi definido como texto)
print(g) #escrever a variável g
print(type(g)) #serve para escrever o tipo de varável que é "g" (conferindo se foi definido como texto)
print(f+g) #escrever as variáveis f e g
print(f+' '+g) #se queremos que mostre f e g escrito separado temos que usar ' ' ou " "

Fábio
<class 'str'>
Gabriel
<class 'str'>
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [14]:
a == 1 #verifica se o valor de "a" é igual a 1

True

In [19]:
h = (a==1) #definindo h como a verificação (se o valor de "a" é igual a 1)
print(h) #escrever a variável h
type(h) #serve para escrever o tipo de varável que é "h"

True


bool

In [20]:
h = (a==2) #definindo h como a verificação (se o valor de "a" é igual a 2)
print(h) #escrever a variável h
type(h) #serve para escrever o tipo de varável que é "h"

False


bool

In [21]:
i = True #está atribuindo o valor booleano verdadeiro (True) à variável i
type(i) #serve para escrever o tipo de varável que é "i"

bool

In [22]:
ii = 'True' #está atribuindo à variável f o texto "True", quando usamos '' entende-se que a variável é texto
type(ii) #serve para escrever o tipo de varável que é "ii"

str

## Operação de comparação

In [24]:
# Operação ==
a==b #comparando se a variável "a" é igual a variável "b" definidas anteriormente

True

In [30]:
# Operação ><
a>b #comparando se a variável "a" é maior que a variável "b"

False

In [31]:
# Operação ><
a<b #comparando se a variável "a" é menor que a variável "b"

False

In [32]:
# Operação !=
a!=b #comparando se a variável "a" é diferente da variável "b"

False

In [33]:
# Operação >= ou <=
a>=b #comparando se a variável "a" é maior ou igual a variável "b"

True

## Operações matemáticas

In [34]:
# Soma 
a+b #somando o valor da variável "a" com o valor da variável "b"

2.0

In [35]:
# Soma e atribui valor
ab = a+b #atribuindo o valor da soma à variável "ab"
print(ab) #escrever a variável ab

2.0


In [37]:
# Multiplicação
l = a*b # Não use  como variável 
print("Não use l como nome de variável") #evitar usar a letra "l" como nome de variável por causa da sua semelhança visual com o número "1"
j = a*b #atribuindo o valor da multiplicação da variável a com a variável b à variável "j"
print(j) #escrever a variável j

Não use l como nome de variável
1.0


In [38]:
# Divisão
a/b #dividindo o valor da variável "a" pelo o valor da variável "b"

1.0

In [39]:
# Potencia
5**2 #comando para fazer o cálculo de 5²

25

In [40]:
# Operações matemáticas com a bibliotéca math
import math #importando o módulo math

math.exp(10) #chamando a função exp() desse módulo com o argumento 10

22026.465794806718

In [41]:
math.exp(0) #chamando a função exp() desse módulo com o argumento 0

1.0

In [42]:
math.exp(a) #chamando a função exp() desse módulo com a variável "a"

2.718281828459045

In [43]:
math.exp(-10) #chamando a função exp() desse módulo com o argumento -10

4.5399929762484854e-05

In [44]:
import math as mt #importando o módulo math e o está renomeando como "mt"
mt.log(c) #chamando a função log() desse módulo com a variável "c"

0.0

In [45]:
mt.log10(100) #chamando a função log() desse módulo com o argumento 100

2.0

## Listas

In [46]:
myFirstList = [1,2,3] #criando uma lista chamada "myFirstList" com os elementos 1, 2 e 3
print(myFirstList) #escrever a lista "myFirstList"

[1, 2, 3]


In [47]:
# Acessando valores da lista pelo index
print(myFirstList[0]) #escrever o primeiro elemento da lista "myFirstList"
print(myFirstList[2]) #escrever o terceiro elemento da lista "myFirstList"

1
3


In [48]:
myFirstList==a #comparando se a lista "myFirstList" é igual a variável "a"

False

In [49]:
myFirstList[0]==a #comparando se o primeiro elemento da lista "myFirstList" é igual a variável "a"

True

In [50]:
mySecList = [1,a,'c'] #criando uma lista chamada "mySecList" com os elementos: o número 1, o valor da variável a e o texto (str) 'c'
print(mySecList) #escrever a lista "mySecList"

[1, 1, 'c']


In [51]:
type(mySecList) #serve para escrever o tipo de variável que é "mySecList"

list

In [52]:
type(mySecList[2]) #serve para escrever o tipo de variável que é o terceiro elemento da lista "mySecList"

str

In [53]:
type(mySecList[1]) #serve para escrever o tipo de variável que é o segundo elemento da lista "mySecList"

int

In [54]:
type(mySecList[0]) #serve para escrever o tipo de variável que é o primeiro elemento da lista "mySecList"

int

## Caminhos = path

In [59]:
path = r"C:\Users\Suelen Silva\Documents\CONTROLE_24.1\ENS5173_202401" #define uma variável chamada "path" com o valor da string que representa um caminho de diretório no sistema Windows
# o "r" antes do caminho representa serve para o caminho no Windows, onde barras invertidas (\) são usadas como separadores de diretório
print(path) #escrever a variável chamada "path"

C:\Users\Suelen Silva\Documents\CONTROLE_24.1\ENS5173_202401


In [60]:
path = "C:/Users/Suelen Silva/Documents/CONTROLE_24.1/ENS5173_202401" #define uma variável chamada "path" com o valor da string que representa um caminho de diretório no sistema Windows
print(path) #escrever a variável chamada "path"

C:/Users/Suelen Silva/Documents/CONTROLE_24.1/ENS5173_202401


In [62]:
import os #importando o módulo "os" para interagir com o sistema operacional
os.listdir(path) #listar os arquivos no diretório especificado pela variável "path"

#NOTA: pq ficou na vertical? tem algum problema?

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Atividade01_Etapa01.ipynb',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [63]:
os.listdir(path)[0] #selecionar primeiro arquivo listado na variável "path", lembrando se usar "os" para interagir com o sistema operacional

'.git'

In [67]:
path+"/"+os.listdir(path)[0] #Concatenando (combinar duas ou mais strings em uma única string) caminhos

#NOTA: aqui estou dando um comando para criar a combinação

'C:/Users/Suelen Silva/Documents/CONTROLE_24.1/ENS5173_202401/.git'

In [66]:
#NOTA: aqui estou pedindo para escrever a combinação

print(path+"/"+os.listdir(path)[0])

C:/Users/Suelen Silva/Documents/CONTROLE_24.1/ENS5173_202401/.git


In [68]:
os.listdir(path+"/"+os.listdir(path)[0]) #listar os arquivos no diretório especificado pelo caminho concatenado

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [69]:
os.getcwd() #obter o diretório de trabalho atual do processo

'C:\\Users\\Suelen Silva\\Documents\\CONTROLE_24.1\\ENS5173_202401'

In [72]:
os.chdir('C:\\Users\\Suelen Silva\\Documents\\CONTROLE_24.1\\') #mudar o diretório de trabalho atual para o caminho especificado

In [74]:
os.getcwd() #para conferir se mudou

'C:\\Users\\Suelen Silva\\Documents\\CONTROLE_24.1'

In [78]:
# Criando diretório
new_path = os.getcwd()+'/test' #comando para criar uma nova pasta no diretório atual com o nome "test"
#mas primeiro verifica-se se o diretório já existe

if os.path.isdir(new_path): 
    print('diretório já existe') #Se sim, imprime "diretório já existe"
else:
    print('Criando diretório '+new_path) #Caso contrário, imprime 'Criando diretório' seguido do caminho do novo diretório
    os.mkdir(new_path) #para criar o diretório

Criando diretório C:\Users\Suelen Silva\Documents\CONTROLE_24.1/test


In [79]:
# Criei uma pasta test2 e agora vou testar a função "diretório já existe"
new_path = os.getcwd()+'/test2' #comando para criar uma nova pasta no diretório atual com o nome "test2"
#mas primeiro verifica-se se o diretório já existe

if os.path.isdir(new_path): 
    print('diretório já existe') #Se sim, imprime "diretório já existe"
else:
    print('Criando diretório '+new_path) #Caso contrário, imprime 'Criando diretório' seguido do caminho do novo diretório
    os.mkdir(new_path) #para criar o diretório

diretório já existe


## Numpy arrays e Pandas DataFrames

In [81]:
import numpy as np #importando a biblioteca NumPy com o nome np 
n = np.array(0) #criando uma variável numpy chamada n com o valor 0
type(n) #serve para escrever o tipo de variável que é "n"

#o tipo da variável n é <class 'numpy.ndarray'>, indicando que n é uma matriz NumPy

numpy.ndarray

In [82]:
myThirdList=[1,2,3,10,20,55] #criando uma lista chamada "myThirdList" com os elementos 1,2,3,10,20 e 55
n = np.array(myThirdList) #criando uma variável numpy a partir da lista "myThirdList"
print(n) #escrever a lista "myThirdList"

[ 1  2  3 10 20 55]


In [83]:

n = np.random.rand(10,10) #utilizando a biblioteca NumPy para criar uma matriz 10x10 preenchida com números aleatórios entre 0 e 1
print(n) #escrever a matriz
print(n.shape) #escrever as dimensões da matriz "n"

[[0.4034979  0.83995636 0.4991784  0.01014463 0.40378563 0.15151058
  0.68747332 0.09663867 0.8333104  0.36357639]
 [0.73309204 0.61941242 0.3424638  0.60614383 0.03743412 0.15997229
  0.36108948 0.27388801 0.85536467 0.79421785]
 [0.34440549 0.77287609 0.32802111 0.14612376 0.56676989 0.77941086
  0.52058225 0.84189127 0.3058645  0.8785943 ]
 [0.16907673 0.66208957 0.85875858 0.77096716 0.46127196 0.22154524
  0.55591854 0.37149865 0.47580774 0.09266018]
 [0.21086726 0.87082176 0.81605942 0.53394321 0.00826068 0.13803703
  0.81610971 0.81222773 0.88868118 0.48427459]
 [0.82956908 0.22338722 0.12714842 0.04711663 0.19395073 0.74580455
  0.40536332 0.4732596  0.81850746 0.95005675]
 [0.00818275 0.87065771 0.29768168 0.76244022 0.18868835 0.43096026
  0.3830915  0.6954469  0.48050336 0.41282523]
 [0.20821238 0.11366606 0.2681954  0.36387287 0.95639075 0.68309399
  0.4836313  0.2117978  0.30526002 0.53590881]
 [0.92956065 0.86753969 0.56366524 0.61543535 0.493082   0.03171894
  0.07484431

In [84]:
n[0,:] #acessando a primeira linha da matriz em todas as colunas

array([0.4034979 , 0.83995636, 0.4991784 , 0.01014463, 0.40378563,
       0.15151058, 0.68747332, 0.09663867, 0.8333104 , 0.36357639])

In [85]:
n[:,0] #acessando a primeira coluna da matriz em todas as linhas

array([0.4034979 , 0.83995636, 0.4991784 , 0.01014463, 0.40378563,
       0.15151058, 0.68747332, 0.09663867, 0.8333104 , 0.36357639])

In [86]:
n[:,1:5] #acessando as colunas da matriz da segunda (índice 1) até a quinta (índice 4) em todas as linhas

array([[0.83995636, 0.4991784 , 0.01014463, 0.40378563],
       [0.61941242, 0.3424638 , 0.60614383, 0.03743412],
       [0.77287609, 0.32802111, 0.14612376, 0.56676989],
       [0.66208957, 0.85875858, 0.77096716, 0.46127196],
       [0.87082176, 0.81605942, 0.53394321, 0.00826068],
       [0.22338722, 0.12714842, 0.04711663, 0.19395073],
       [0.87065771, 0.29768168, 0.76244022, 0.18868835],
       [0.11366606, 0.2681954 , 0.36387287, 0.95639075],
       [0.86753969, 0.56366524, 0.61543535, 0.493082  ],
       [0.62378019, 0.37614918, 0.08606338, 0.54787216]])

In [87]:
n[0,1:5] #acessando as colunas da matriz da segunda (índice 1) até a quinta (índice 4) na primeira linha

array([0.83995636, 0.4991784 , 0.01014463, 0.40378563])

In [88]:
n[0,-1] #acessando a última coluna da matriz (índice -1) na primeira linha (índice 0)

0.3635763908994317

In [89]:
n[0,4:-1] #acessando da quinta até a penúltima coluna da matriz (índice 4:-1) na primeira linha (índice 0)

array([0.40378563, 0.15151058, 0.68747332, 0.09663867, 0.8333104 ])

In [90]:
n[0,4:] #acessando da quinta até a última coluna da matriz (índice 4:) na primeira linha (índice 0)

array([0.40378563, 0.15151058, 0.68747332, 0.09663867, 0.8333104 ,
       0.36357639])

In [91]:
an = np.log(n*5) #multiplica todos os elementos da matriz n por 5 e armazena na variável "an"
print(an) #escrever as dimensões da matriz "an"

[[ 0.70185391  1.43503257  0.91464619 -2.98137281  0.70256676 -0.27766191
   1.23470566 -0.72733839  1.42708883  0.59767206]
 [ 1.29895389  1.13045396  0.5378486   1.10879994 -1.67573482 -0.22331678
   0.59080843  0.31440194  1.45321053  1.37904042]
 [ 0.54350234  1.35180137  0.49476059 -0.31386343  1.04163602  1.36022096
   0.95663053  1.43733351  0.42482484  1.48000587]
 [-0.16796475  1.19708348  1.45717047  1.34932841  0.83567045  0.10230944
   1.02230441  0.61922788  0.86669649 -0.76937855]
 [ 0.05291149  1.47111995  1.40616981  0.98197211 -3.18681039 -0.37079537
   1.40623143  1.40146339  1.49142117  0.88433471]
 [ 1.42258902  0.11058932 -0.45296228 -1.4456913  -0.0307132   1.3161462
   0.70646637  0.86132671  1.40916514  1.55820435]
 [-3.19628907  1.47093155  0.39770735  1.33820674 -0.05822064  0.76769853
   0.6499565   1.24623729  0.87651686  0.72470698]
 [ 0.04024123 -0.56505252  0.29339845  0.59848719  1.5648492   1.2283151
   0.88300548  0.05731467  0.42284656  0.98564664]
 [